-- MySQL Script generated by MySQL Workbench
-- Thu Oct 18 14:14:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alojamientos_rurales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alojamientos_rurales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alojamientos_rurales` DEFAULT CHARACTER SET utf8 ;
USE `alojamientos_rurales` ;

-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`personas` (
  `idpersonas` INT NOT NULL AUTO_INCREMENT,
  `trabaja_en_idalojamiento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `nif` CHAR(9) NOT NULL,
  `codigo_personal` CHAR(10) NOT NULL,
  PRIMARY KEY (`idpersonas`),
  INDEX `fk_personas_alojamiento_idx` (`trabaja_en_idalojamiento` ASC),
  UNIQUE INDEX `codigo_personal_UNIQUE` (`codigo_personal` ASC),
  CONSTRAINT `fk_personas_alojamiento`
    FOREIGN KEY (`trabaja_en_idalojamiento`)
    REFERENCES `alojamientos_rurales`.`alojamientos` (`idalojamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`alojamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`alojamientos` (
  `idalojamiento` INT NOT NULL AUTO_INCREMENT,
  `persona_de_contacto_idpersonas` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` CHAR(9) NULL,
  PRIMARY KEY (`idalojamiento`),
  INDEX `fk_alojamiento_personas1_idx` (`persona_de_contacto_idpersonas` ASC),
  CONSTRAINT `fk_alojamiento_personas1`
    FOREIGN KEY (`persona_de_contacto_idpersonas`)
    REFERENCES `alojamientos_rurales`.`personas` (`idpersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`habitaciones` (
  `idhabitaciones` INT NOT NULL AUTO_INCREMENT,
  `pertenece_a_idalojamiento` INT NOT NULL,
  `numero_habitacion` CHAR(3) NULL,
  `tipo` VARCHAR(12) NOT NULL,
  `cuarto_de_bano` TINYINT NOT NULL,
  `precio` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idhabitaciones`),
  INDEX `fk_habitaciones_alojamiento1_idx` (`pertenece_a_idalojamiento` ASC),
  CONSTRAINT `fk_habitaciones_alojamiento1`
    FOREIGN KEY (`pertenece_a_idalojamiento`)
    REFERENCES `alojamientos_rurales`.`alojamientos` (`idalojamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`actividades` (
  `idactividades` INT NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(3) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `nivel_dificultad` TINYINT NOT NULL,
  PRIMARY KEY (`idactividades`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`alojamiento_has_actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`alojamiento_has_actividades` (
  `alojamientos_idalojamiento` INT NOT NULL,
  `actividades_idactividades` INT NOT NULL,
  `dia_semana` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`alojamientos_idalojamiento`, `actividades_idactividades`, `dia_semana`),
  INDEX `fk_alojamiento_has_actividades_actividades1_idx` (`actividades_idactividades` ASC),
  INDEX `fk_alojamiento_has_actividades_alojamiento1_idx` (`alojamientos_idalojamiento` ASC),
  CONSTRAINT `fk_alojamiento_has_actividades_alojamiento1`
    FOREIGN KEY (`alojamientos_idalojamiento`)
    REFERENCES `alojamientos_rurales`.`alojamientos` (`idalojamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alojamiento_has_actividades_actividades1`
    FOREIGN KEY (`actividades_idactividades`)
    REFERENCES `alojamientos_rurales`.`actividades` (`idactividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
