-- MySQL Script generated by MySQL Workbench
-- Thu Oct 18 13:12:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alojamientos_rurales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alojamientos_rurales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alojamientos_rurales` DEFAULT CHARACTER SET utf8 ;
USE `alojamientos_rurales` ;

-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`Alojamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`Alojamientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `persona_contacto` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`Personal` (
  `CodigoPersonal` INT NOT NULL AUTO_INCREMENT,
  `NIF` VARCHAR(11) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Alojamientos_id` INT NOT NULL,
  PRIMARY KEY (`CodigoPersonal`),
  INDEX `fk_Personal_Alojamientos_idx` (`Alojamientos_id` ASC),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC),
  CONSTRAINT `fk_Personal_Alojamientos`
    FOREIGN KEY (`Alojamientos_id`)
    REFERENCES `alojamientos_rurales`.`Alojamientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`Habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`Habitaciones` (
  `idHabitacion` INT NOT NULL,
  `tamano` VARCHAR(45) NULL,
  `cuarto_de_bano` VARCHAR(10) NULL,
  `precio` DECIMAL NULL,
  `Alojamientos_id` INT NOT NULL,
  PRIMARY KEY (`idHabitacion`),
  INDEX `fk_Habitaciones_Alojamientos1_idx` (`Alojamientos_id` ASC),
  CONSTRAINT `fk_Habitaciones_Alojamientos1`
    FOREIGN KEY (`Alojamientos_id`)
    REFERENCES `alojamientos_rurales`.`Alojamientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`Actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`Actividades` (
  `idActividades` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `nivel` TINYINT NULL,
  `codigo` CHAR(3) NULL,
  PRIMARY KEY (`idActividades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alojamientos_rurales`.`Alojamientos_has_Actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alojamientos_rurales`.`Alojamientos_has_Actividades` (
  `Alojamientos_id` INT NOT NULL,
  `Actividades_idActividades` INT NOT NULL,
  `dia_semana` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Alojamientos_id`, `Actividades_idActividades`),
  INDEX `fk_Alojamientos_has_Actividades_Actividades1_idx` (`Actividades_idActividades` ASC),
  INDEX `fk_Alojamientos_has_Actividades_Alojamientos1_idx` (`Alojamientos_id` ASC),
  CONSTRAINT `fk_Alojamientos_has_Actividades_Alojamientos1`
    FOREIGN KEY (`Alojamientos_id`)
    REFERENCES `alojamientos_rurales`.`Alojamientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alojamientos_has_Actividades_Actividades1`
    FOREIGN KEY (`Actividades_idActividades`)
    REFERENCES `alojamientos_rurales`.`Actividades` (`idActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
