-- MySQL Script generated by MySQL Workbench
-- Tue Oct 16 09:56:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema empadronamiento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empadronamiento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empadronamiento` DEFAULT CHARACTER SET utf8 ;
USE `empadronamiento` ;

-- -----------------------------------------------------
-- Table `empadronamiento`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empadronamiento`.`municipios` (
  `idmunicipios` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idmunicipios`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empadronamiento`.`viviendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empadronamiento`.`viviendas` (
  `idviviendas` INT NOT NULL AUTO_INCREMENT,
  `pertenece_municipio_id` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idviviendas`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_viviendas_municipios1_idx` (`pertenece_municipio_id` ASC),
  CONSTRAINT `fk_viviendas_municipios1`
    FOREIGN KEY (`pertenece_municipio_id`)
    REFERENCES `empadronamiento`.`municipios` (`idmunicipios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empadronamiento`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empadronamiento`.`personas` (
  `idpersonas` INT NOT NULL AUTO_INCREMENT,
  `habitar_vivienda_id` INT NULL,
  `empadronado_en_vivienda_id` INT NOT NULL,
  `dni` CHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersonas`),
  INDEX `fk_personas_viviendas_idx` (`habitar_vivienda_id` ASC),
  INDEX `fk_personas_viviendas1_idx` (`empadronado_en_vivienda_id` ASC),
  CONSTRAINT `fk_personas_viviendas`
    FOREIGN KEY (`habitar_vivienda_id`)
    REFERENCES `empadronamiento`.`viviendas` (`idviviendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_viviendas1`
    FOREIGN KEY (`empadronado_en_vivienda_id`)
    REFERENCES `empadronamiento`.`viviendas` (`idviviendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empadronamiento`.`personas_propiedad_viviendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empadronamiento`.`personas_propiedad_viviendas` (
  `personas_idpersonas` INT NOT NULL,
  `viviendas_idviviendas` INT NOT NULL,
  PRIMARY KEY (`personas_idpersonas`, `viviendas_idviviendas`),
  INDEX `fk_personas_has_viviendas_viviendas1_idx` (`viviendas_idviviendas` ASC),
  INDEX `fk_personas_has_viviendas_personas1_idx` (`personas_idpersonas` ASC),
  CONSTRAINT `fk_personas_has_viviendas_personas1`
    FOREIGN KEY (`personas_idpersonas`)
    REFERENCES `empadronamiento`.`personas` (`idpersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_has_viviendas_viviendas1`
    FOREIGN KEY (`viviendas_idviviendas`)
    REFERENCES `empadronamiento`.`viviendas` (`idviviendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
